name: move draft and update metadata

runs:
  using: "composite"
  steps:
    - name: move draft and update metadata
      run: |
        draft_files=($(grep -xl 'Draft: true' $(git ls-files -mo --exclude-standard)))
        for file in ${draft_files[@]}; do
          entry_id=$(yq --front-matter=extract '.EditURL' "$file" | grep -oP '[^/]+\d')
          yq --front-matter=process -i 'del(.Date,.URL)' "$file" 
          mv "$file" "draft_entries/$entry_id.${file##*.}"
        done
      shell: bash
