name: delete draft files

runs:
  using: "composite"
  steps:
    - name: delete draft files
      run: |
        draft_files=($(grep -xl 'Draft: true' $(git ls-files -mo --exclude-standard)))
        for file in ${draft_files[@]}; do
          rm "$file"
        done
      shell: bash
