name: "[Reusable workflows] pull from hatenablog"

on:
  workflow_call:
    inputs:
      BLOG_DOMAIN:
        required: true
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  pull:
    runs-on: ubuntu-latest
    env:
      BLOGSYNC_PASSWORD: ${{ secrets.OWNER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup
        uses: hatena/hatenablog-workflows/.github/actions/setup@v1
      - name: pull
        run: |
          blogsync pull ${{ inputs.BLOG_DOMAIN }}
      - name: delete draft files
        run: |
          target=$(git ls-files -mo --exclude-standard | xargs grep -xl 'Draft: true')
          IFS=" " read -r -a draft_files <<< "$(echo "$target" | xargs)"
          for file in "${draft_files[@]}"; do
            rm "$file"
          done
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: blogsync pull
          branch: blogsync-pull
          commit-message: |
            blogsync pull
          body: |
            blogsync pull
          labels: |
            skip-push
          delete-branch: true
